version: 2

sources:
  - name: source_bronze
    database: loandb
    schema: bronze
    tables:
      - name: loans
      - name: borrowers
      - name: servicers
      - name: properties
      - name: loan_payments
      - name: states

  - name: source_silver
    database: loandb
    schema: silver
    tables:
      - name: loans
      - name: borrowers
      - name: servicers
      - name: properties
      - name: loan_payments
      - name: states
